# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u4e1a\u52a1\u540d\u79f0')),
                ('creator', models.CharField(max_length=30, verbose_name='\u521b\u5efa\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('members', models.IntegerField(default=0, verbose_name='\u7528\u6237\u6570')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u4e1a\u52a1\u7ec4')),
                ('leader', models.CharField(max_length=30, verbose_name='\u8d1f\u8d23\u4eba')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Group', verbose_name='\u6240\u5c5e\u4e1a\u52a1\u7ec4'),
        ),
    ]
